create database bd_sistema_bancario;
create table client(name text);
create table finance(balance real);
create table contact(phone integer);
create table address (residence varchar);
create table category (income real);
create table cliente (nome_cliente text, cidade_cliente text, endereco_cliente varchar[15]);
create table conta (numero_conta integer[10], nome_agencia varchar[15], saldo integer);
create table emprestimo (nome_agencia text, valor real );
create table agencia (nome_agencia text, cidade_agencia text, depositos integer );
drop table address, category, client, contact, finance;
alter table cliente rename to tbl_cliente;
alter table conta rename to tbl_conta;
alter table emprestimo rename to tbl_emprestimo;
alter table agencia rename to tbl_agencia;
alter table  tbl_cliente add column idade integer[2];
alter table  tbl_cliente add column cpf integer[15];
alter table  tbl_emprestimo add column numero_emprestimo integer[15];
alter table  tbl_emprestimo rename column cidade_agencia to endereco_agencia;